// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data/base.proto

package top.itcat.pb_gen.common;

public final class Base {
    private Base() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    /**
     * Protobuf enum {@code SuitableRangeEnum}
     */
    public enum SuitableRangeEnum
            implements com.google.protobuf.ProtocolMessageEnum {
        /**
         * <code>SuitableRangeEnum_Personal = 0;</code>
         */
        SuitableRangeEnum_Personal(0),
        /**
         * <code>SuitableRangeEnum_Depart = 1;</code>
         */
        SuitableRangeEnum_Depart(1),
        /**
         * <code>SuitableRangeEnum_Hospital = 2;</code>
         */
        SuitableRangeEnum_Hospital(2),
        UNRECOGNIZED(-1),
        ;

        /**
         * <code>SuitableRangeEnum_Personal = 0;</code>
         */
        public static final int SuitableRangeEnum_Personal_VALUE = 0;
        /**
         * <code>SuitableRangeEnum_Depart = 1;</code>
         */
        public static final int SuitableRangeEnum_Depart_VALUE = 1;
        /**
         * <code>SuitableRangeEnum_Hospital = 2;</code>
         */
        public static final int SuitableRangeEnum_Hospital_VALUE = 2;


        public final int getNumber() {
            if (this == UNRECOGNIZED) {
                throw new java.lang.IllegalArgumentException(
                        "Can't get the number of an unknown enum value.");
            }
            return value;
        }

        /**
         * @deprecated Use {@link #forNumber(int)} instead.
         */
        @java.lang.Deprecated
        public static SuitableRangeEnum valueOf(int value) {
            return forNumber(value);
        }

        public static SuitableRangeEnum forNumber(int value) {
            switch (value) {
                case 0:
                    return SuitableRangeEnum_Personal;
                case 1:
                    return SuitableRangeEnum_Depart;
                case 2:
                    return SuitableRangeEnum_Hospital;
                default:
                    return null;
            }
        }

        public static com.google.protobuf.Internal.EnumLiteMap<SuitableRangeEnum>
        internalGetValueMap() {
            return internalValueMap;
        }

        private static final com.google.protobuf.Internal.EnumLiteMap<
                SuitableRangeEnum> internalValueMap =
                new com.google.protobuf.Internal.EnumLiteMap<SuitableRangeEnum>() {
                    public SuitableRangeEnum findValueByNumber(int number) {
                        return SuitableRangeEnum.forNumber(number);
                    }
                };

        public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
            return getDescriptor().getValues().get(ordinal());
        }

        public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
            return getDescriptor();
        }

        public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
            return top.itcat.pb_gen.common.Base.getDescriptor().getEnumTypes().get(0);
        }

        private static final SuitableRangeEnum[] VALUES = values();

        public static SuitableRangeEnum valueOf(
                com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
            if (desc.getType() != getDescriptor()) {
                throw new java.lang.IllegalArgumentException(
                        "EnumValueDescriptor is not for this type.");
            }
            if (desc.getIndex() == -1) {
                return UNRECOGNIZED;
            }
            return VALUES[desc.getIndex()];
        }

        private final int value;

        private SuitableRangeEnum(int value) {
            this.value = value;
        }

        // @@protoc_insertion_point(enum_scope:SuitableRangeEnum)
    }

    /**
     * Protobuf enum {@code ServiceObject}
     */
    public enum ServiceObject
            implements com.google.protobuf.ProtocolMessageEnum {
        /**
         * <pre>
         * 门诊
         * </pre>
         *
         * <code>Normal = 0;</code>
         */
        Normal(0),
        /**
         * <code>Emergency = 1;</code>
         */
        Emergency(1),
        UNRECOGNIZED(-1),
        ;

        /**
         * <pre>
         * 门诊
         * </pre>
         *
         * <code>Normal = 0;</code>
         */
        public static final int Normal_VALUE = 0;
        /**
         * <code>Emergency = 1;</code>
         */
        public static final int Emergency_VALUE = 1;


        public final int getNumber() {
            if (this == UNRECOGNIZED) {
                throw new java.lang.IllegalArgumentException(
                        "Can't get the number of an unknown enum value.");
            }
            return value;
        }

        /**
         * @deprecated Use {@link #forNumber(int)} instead.
         */
        @java.lang.Deprecated
        public static ServiceObject valueOf(int value) {
            return forNumber(value);
        }

        public static ServiceObject forNumber(int value) {
            switch (value) {
                case 0:
                    return Normal;
                case 1:
                    return Emergency;
                default:
                    return null;
            }
        }

        public static com.google.protobuf.Internal.EnumLiteMap<ServiceObject>
        internalGetValueMap() {
            return internalValueMap;
        }

        private static final com.google.protobuf.Internal.EnumLiteMap<
                ServiceObject> internalValueMap =
                new com.google.protobuf.Internal.EnumLiteMap<ServiceObject>() {
                    public ServiceObject findValueByNumber(int number) {
                        return ServiceObject.forNumber(number);
                    }
                };

        public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
            return getDescriptor().getValues().get(ordinal());
        }

        public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
            return getDescriptor();
        }

        public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
            return top.itcat.pb_gen.common.Base.getDescriptor().getEnumTypes().get(1);
        }

        private static final ServiceObject[] VALUES = values();

        public static ServiceObject valueOf(
                com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
            if (desc.getType() != getDescriptor()) {
                throw new java.lang.IllegalArgumentException(
                        "EnumValueDescriptor is not for this type.");
            }
            if (desc.getIndex() == -1) {
                return UNRECOGNIZED;
            }
            return VALUES[desc.getIndex()];
        }

        private final int value;

        private ServiceObject(int value) {
            this.value = value;
        }

        // @@protoc_insertion_point(enum_scope:ServiceObject)
    }

    public interface BaseResponseOrBuilder extends
            // @@protoc_insertion_point(interface_extends:BaseResponse)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>int32 code = 1;</code>
         */
        int getCode();

        /**
         * <code>string msg = 2;</code>
         */
        java.lang.String getMsg();

        /**
         * <code>string msg = 2;</code>
         */
        com.google.protobuf.ByteString
        getMsgBytes();
    }

    /**
     * Protobuf type {@code BaseResponse}
     */
    public static final class BaseResponse extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:BaseResponse)
            BaseResponseOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use BaseResponse.newBuilder() to construct.
        private BaseResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private BaseResponse() {
            code_ = 0;
            msg_ = "";
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private BaseResponse(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 8: {

                            code_ = input.readInt32();
                            break;
                        }
                        case 18: {
                            java.lang.String s = input.readStringRequireUtf8();

                            msg_ = s;
                            break;
                        }
                        default: {
                            if (!parseUnknownFieldProto3(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return top.itcat.pb_gen.common.Base.internal_static_BaseResponse_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return top.itcat.pb_gen.common.Base.internal_static_BaseResponse_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            top.itcat.pb_gen.common.Base.BaseResponse.class, top.itcat.pb_gen.common.Base.BaseResponse.Builder.class);
        }

        public static final int CODE_FIELD_NUMBER = 1;
        private int code_;

        /**
         * <code>int32 code = 1;</code>
         */
        public int getCode() {
            return code_;
        }

        public static final int MSG_FIELD_NUMBER = 2;
        private volatile java.lang.Object msg_;

        /**
         * <code>string msg = 2;</code>
         */
        public java.lang.String getMsg() {
            java.lang.Object ref = msg_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                msg_ = s;
                return s;
            }
        }

        /**
         * <code>string msg = 2;</code>
         */
        public com.google.protobuf.ByteString
        getMsgBytes() {
            java.lang.Object ref = msg_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                msg_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (code_ != 0) {
                output.writeInt32(1, code_);
            }
            if (!getMsgBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, msg_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (code_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(1, code_);
            }
            if (!getMsgBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, msg_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof top.itcat.pb_gen.common.Base.BaseResponse)) {
                return super.equals(obj);
            }
            top.itcat.pb_gen.common.Base.BaseResponse other = (top.itcat.pb_gen.common.Base.BaseResponse) obj;

            boolean result = true;
            result = result && (getCode()
                    == other.getCode());
            result = result && getMsg()
                    .equals(other.getMsg());
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + CODE_FIELD_NUMBER;
            hash = (53 * hash) + getCode();
            hash = (37 * hash) + MSG_FIELD_NUMBER;
            hash = (53 * hash) + getMsg().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static top.itcat.pb_gen.common.Base.BaseResponse parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static top.itcat.pb_gen.common.Base.BaseResponse parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static top.itcat.pb_gen.common.Base.BaseResponse parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static top.itcat.pb_gen.common.Base.BaseResponse parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static top.itcat.pb_gen.common.Base.BaseResponse parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static top.itcat.pb_gen.common.Base.BaseResponse parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static top.itcat.pb_gen.common.Base.BaseResponse parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static top.itcat.pb_gen.common.Base.BaseResponse parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static top.itcat.pb_gen.common.Base.BaseResponse parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static top.itcat.pb_gen.common.Base.BaseResponse parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static top.itcat.pb_gen.common.Base.BaseResponse parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static top.itcat.pb_gen.common.Base.BaseResponse parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(top.itcat.pb_gen.common.Base.BaseResponse prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code BaseResponse}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:BaseResponse)
                top.itcat.pb_gen.common.Base.BaseResponseOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return top.itcat.pb_gen.common.Base.internal_static_BaseResponse_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return top.itcat.pb_gen.common.Base.internal_static_BaseResponse_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                top.itcat.pb_gen.common.Base.BaseResponse.class, top.itcat.pb_gen.common.Base.BaseResponse.Builder.class);
            }

            // Construct using top.itcat.pb_gen.common.Base.BaseResponse.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                code_ = 0;

                msg_ = "";

                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return top.itcat.pb_gen.common.Base.internal_static_BaseResponse_descriptor;
            }

            @java.lang.Override
            public top.itcat.pb_gen.common.Base.BaseResponse getDefaultInstanceForType() {
                return top.itcat.pb_gen.common.Base.BaseResponse.getDefaultInstance();
            }

            @java.lang.Override
            public top.itcat.pb_gen.common.Base.BaseResponse build() {
                top.itcat.pb_gen.common.Base.BaseResponse result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public top.itcat.pb_gen.common.Base.BaseResponse buildPartial() {
                top.itcat.pb_gen.common.Base.BaseResponse result = new top.itcat.pb_gen.common.Base.BaseResponse(this);
                result.code_ = code_;
                result.msg_ = msg_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return (Builder) super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof top.itcat.pb_gen.common.Base.BaseResponse) {
                    return mergeFrom((top.itcat.pb_gen.common.Base.BaseResponse) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(top.itcat.pb_gen.common.Base.BaseResponse other) {
                if (other == top.itcat.pb_gen.common.Base.BaseResponse.getDefaultInstance()) return this;
                if (other.getCode() != 0) {
                    setCode(other.getCode());
                }
                if (!other.getMsg().isEmpty()) {
                    msg_ = other.msg_;
                    onChanged();
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                top.itcat.pb_gen.common.Base.BaseResponse parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (top.itcat.pb_gen.common.Base.BaseResponse) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int code_;

            /**
             * <code>int32 code = 1;</code>
             */
            public int getCode() {
                return code_;
            }

            /**
             * <code>int32 code = 1;</code>
             */
            public Builder setCode(int value) {

                code_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>int32 code = 1;</code>
             */
            public Builder clearCode() {

                code_ = 0;
                onChanged();
                return this;
            }

            private java.lang.Object msg_ = "";

            /**
             * <code>string msg = 2;</code>
             */
            public java.lang.String getMsg() {
                java.lang.Object ref = msg_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    msg_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string msg = 2;</code>
             */
            public com.google.protobuf.ByteString
            getMsgBytes() {
                java.lang.Object ref = msg_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    msg_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string msg = 2;</code>
             */
            public Builder setMsg(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                msg_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string msg = 2;</code>
             */
            public Builder clearMsg() {

                msg_ = getDefaultInstance().getMsg();
                onChanged();
                return this;
            }

            /**
             * <code>string msg = 2;</code>
             */
            public Builder setMsgBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                msg_ = value;
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFieldsProto3(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:BaseResponse)
        }

        // @@protoc_insertion_point(class_scope:BaseResponse)
        private static final top.itcat.pb_gen.common.Base.BaseResponse DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new top.itcat.pb_gen.common.Base.BaseResponse();
        }

        public static top.itcat.pb_gen.common.Base.BaseResponse getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<BaseResponse>
                PARSER = new com.google.protobuf.AbstractParser<BaseResponse>() {
            @java.lang.Override
            public BaseResponse parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new BaseResponse(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<BaseResponse> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<BaseResponse> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public top.itcat.pb_gen.common.Base.BaseResponse getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface EmptyResponseOrBuilder extends
            // @@protoc_insertion_point(interface_extends:EmptyResponse)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>.BaseResponse base = 1;</code>
         */
        boolean hasBase();

        /**
         * <code>.BaseResponse base = 1;</code>
         */
        top.itcat.pb_gen.common.Base.BaseResponse getBase();

        /**
         * <code>.BaseResponse base = 1;</code>
         */
        top.itcat.pb_gen.common.Base.BaseResponseOrBuilder getBaseOrBuilder();
    }

    /**
     * Protobuf type {@code EmptyResponse}
     */
    public static final class EmptyResponse extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:EmptyResponse)
            EmptyResponseOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use EmptyResponse.newBuilder() to construct.
        private EmptyResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private EmptyResponse() {
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private EmptyResponse(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            top.itcat.pb_gen.common.Base.BaseResponse.Builder subBuilder = null;
                            if (base_ != null) {
                                subBuilder = base_.toBuilder();
                            }
                            base_ = input.readMessage(top.itcat.pb_gen.common.Base.BaseResponse.parser(), extensionRegistry);
                            if (subBuilder != null) {
                                subBuilder.mergeFrom(base_);
                                base_ = subBuilder.buildPartial();
                            }

                            break;
                        }
                        default: {
                            if (!parseUnknownFieldProto3(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return top.itcat.pb_gen.common.Base.internal_static_EmptyResponse_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return top.itcat.pb_gen.common.Base.internal_static_EmptyResponse_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            top.itcat.pb_gen.common.Base.EmptyResponse.class, top.itcat.pb_gen.common.Base.EmptyResponse.Builder.class);
        }

        public static final int BASE_FIELD_NUMBER = 1;
        private top.itcat.pb_gen.common.Base.BaseResponse base_;

        /**
         * <code>.BaseResponse base = 1;</code>
         */
        public boolean hasBase() {
            return base_ != null;
        }

        /**
         * <code>.BaseResponse base = 1;</code>
         */
        public top.itcat.pb_gen.common.Base.BaseResponse getBase() {
            return base_ == null ? top.itcat.pb_gen.common.Base.BaseResponse.getDefaultInstance() : base_;
        }

        /**
         * <code>.BaseResponse base = 1;</code>
         */
        public top.itcat.pb_gen.common.Base.BaseResponseOrBuilder getBaseOrBuilder() {
            return getBase();
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (base_ != null) {
                output.writeMessage(1, getBase());
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (base_ != null) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(1, getBase());
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof top.itcat.pb_gen.common.Base.EmptyResponse)) {
                return super.equals(obj);
            }
            top.itcat.pb_gen.common.Base.EmptyResponse other = (top.itcat.pb_gen.common.Base.EmptyResponse) obj;

            boolean result = true;
            result = result && (hasBase() == other.hasBase());
            if (hasBase()) {
                result = result && getBase()
                        .equals(other.getBase());
            }
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (hasBase()) {
                hash = (37 * hash) + BASE_FIELD_NUMBER;
                hash = (53 * hash) + getBase().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static top.itcat.pb_gen.common.Base.EmptyResponse parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static top.itcat.pb_gen.common.Base.EmptyResponse parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static top.itcat.pb_gen.common.Base.EmptyResponse parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static top.itcat.pb_gen.common.Base.EmptyResponse parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static top.itcat.pb_gen.common.Base.EmptyResponse parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static top.itcat.pb_gen.common.Base.EmptyResponse parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static top.itcat.pb_gen.common.Base.EmptyResponse parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static top.itcat.pb_gen.common.Base.EmptyResponse parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static top.itcat.pb_gen.common.Base.EmptyResponse parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static top.itcat.pb_gen.common.Base.EmptyResponse parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static top.itcat.pb_gen.common.Base.EmptyResponse parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static top.itcat.pb_gen.common.Base.EmptyResponse parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(top.itcat.pb_gen.common.Base.EmptyResponse prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code EmptyResponse}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:EmptyResponse)
                top.itcat.pb_gen.common.Base.EmptyResponseOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return top.itcat.pb_gen.common.Base.internal_static_EmptyResponse_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return top.itcat.pb_gen.common.Base.internal_static_EmptyResponse_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                top.itcat.pb_gen.common.Base.EmptyResponse.class, top.itcat.pb_gen.common.Base.EmptyResponse.Builder.class);
            }

            // Construct using top.itcat.pb_gen.common.Base.EmptyResponse.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                if (baseBuilder_ == null) {
                    base_ = null;
                } else {
                    base_ = null;
                    baseBuilder_ = null;
                }
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return top.itcat.pb_gen.common.Base.internal_static_EmptyResponse_descriptor;
            }

            @java.lang.Override
            public top.itcat.pb_gen.common.Base.EmptyResponse getDefaultInstanceForType() {
                return top.itcat.pb_gen.common.Base.EmptyResponse.getDefaultInstance();
            }

            @java.lang.Override
            public top.itcat.pb_gen.common.Base.EmptyResponse build() {
                top.itcat.pb_gen.common.Base.EmptyResponse result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public top.itcat.pb_gen.common.Base.EmptyResponse buildPartial() {
                top.itcat.pb_gen.common.Base.EmptyResponse result = new top.itcat.pb_gen.common.Base.EmptyResponse(this);
                if (baseBuilder_ == null) {
                    result.base_ = base_;
                } else {
                    result.base_ = baseBuilder_.build();
                }
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return (Builder) super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof top.itcat.pb_gen.common.Base.EmptyResponse) {
                    return mergeFrom((top.itcat.pb_gen.common.Base.EmptyResponse) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(top.itcat.pb_gen.common.Base.EmptyResponse other) {
                if (other == top.itcat.pb_gen.common.Base.EmptyResponse.getDefaultInstance()) return this;
                if (other.hasBase()) {
                    mergeBase(other.getBase());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                top.itcat.pb_gen.common.Base.EmptyResponse parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (top.itcat.pb_gen.common.Base.EmptyResponse) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private top.itcat.pb_gen.common.Base.BaseResponse base_ = null;
            private com.google.protobuf.SingleFieldBuilderV3<
                    top.itcat.pb_gen.common.Base.BaseResponse, top.itcat.pb_gen.common.Base.BaseResponse.Builder, top.itcat.pb_gen.common.Base.BaseResponseOrBuilder> baseBuilder_;

            /**
             * <code>.BaseResponse base = 1;</code>
             */
            public boolean hasBase() {
                return baseBuilder_ != null || base_ != null;
            }

            /**
             * <code>.BaseResponse base = 1;</code>
             */
            public top.itcat.pb_gen.common.Base.BaseResponse getBase() {
                if (baseBuilder_ == null) {
                    return base_ == null ? top.itcat.pb_gen.common.Base.BaseResponse.getDefaultInstance() : base_;
                } else {
                    return baseBuilder_.getMessage();
                }
            }

            /**
             * <code>.BaseResponse base = 1;</code>
             */
            public Builder setBase(top.itcat.pb_gen.common.Base.BaseResponse value) {
                if (baseBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    base_ = value;
                    onChanged();
                } else {
                    baseBuilder_.setMessage(value);
                }

                return this;
            }

            /**
             * <code>.BaseResponse base = 1;</code>
             */
            public Builder setBase(
                    top.itcat.pb_gen.common.Base.BaseResponse.Builder builderForValue) {
                if (baseBuilder_ == null) {
                    base_ = builderForValue.build();
                    onChanged();
                } else {
                    baseBuilder_.setMessage(builderForValue.build());
                }

                return this;
            }

            /**
             * <code>.BaseResponse base = 1;</code>
             */
            public Builder mergeBase(top.itcat.pb_gen.common.Base.BaseResponse value) {
                if (baseBuilder_ == null) {
                    if (base_ != null) {
                        base_ =
                                top.itcat.pb_gen.common.Base.BaseResponse.newBuilder(base_).mergeFrom(value).buildPartial();
                    } else {
                        base_ = value;
                    }
                    onChanged();
                } else {
                    baseBuilder_.mergeFrom(value);
                }

                return this;
            }

            /**
             * <code>.BaseResponse base = 1;</code>
             */
            public Builder clearBase() {
                if (baseBuilder_ == null) {
                    base_ = null;
                    onChanged();
                } else {
                    base_ = null;
                    baseBuilder_ = null;
                }

                return this;
            }

            /**
             * <code>.BaseResponse base = 1;</code>
             */
            public top.itcat.pb_gen.common.Base.BaseResponse.Builder getBaseBuilder() {

                onChanged();
                return getBaseFieldBuilder().getBuilder();
            }

            /**
             * <code>.BaseResponse base = 1;</code>
             */
            public top.itcat.pb_gen.common.Base.BaseResponseOrBuilder getBaseOrBuilder() {
                if (baseBuilder_ != null) {
                    return baseBuilder_.getMessageOrBuilder();
                } else {
                    return base_ == null ?
                            top.itcat.pb_gen.common.Base.BaseResponse.getDefaultInstance() : base_;
                }
            }

            /**
             * <code>.BaseResponse base = 1;</code>
             */
            private com.google.protobuf.SingleFieldBuilderV3<
                    top.itcat.pb_gen.common.Base.BaseResponse, top.itcat.pb_gen.common.Base.BaseResponse.Builder, top.itcat.pb_gen.common.Base.BaseResponseOrBuilder>
            getBaseFieldBuilder() {
                if (baseBuilder_ == null) {
                    baseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                            top.itcat.pb_gen.common.Base.BaseResponse, top.itcat.pb_gen.common.Base.BaseResponse.Builder, top.itcat.pb_gen.common.Base.BaseResponseOrBuilder>(
                            getBase(),
                            getParentForChildren(),
                            isClean());
                    base_ = null;
                }
                return baseBuilder_;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFieldsProto3(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:EmptyResponse)
        }

        // @@protoc_insertion_point(class_scope:EmptyResponse)
        private static final top.itcat.pb_gen.common.Base.EmptyResponse DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new top.itcat.pb_gen.common.Base.EmptyResponse();
        }

        public static top.itcat.pb_gen.common.Base.EmptyResponse getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<EmptyResponse>
                PARSER = new com.google.protobuf.AbstractParser<EmptyResponse>() {
            @java.lang.Override
            public EmptyResponse parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new EmptyResponse(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<EmptyResponse> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<EmptyResponse> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public top.itcat.pb_gen.common.Base.EmptyResponse getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_BaseResponse_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_BaseResponse_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_EmptyResponse_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_EmptyResponse_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\017data/base.proto\")\n\014BaseResponse\022\014\n\004cod" +
                        "e\030\001 \001(\005\022\013\n\003msg\030\002 \001(\t\",\n\rEmptyResponse\022\033\n" +
                        "\004base\030\001 \001(\0132\r.BaseResponse*q\n\021SuitableRa" +
                        "ngeEnum\022\036\n\032SuitableRangeEnum_Personal\020\000\022" +
                        "\034\n\030SuitableRangeEnum_Depart\020\001\022\036\n\032Suitabl" +
                        "eRangeEnum_Hospital\020\002**\n\rServiceObject\022\n" +
                        "\n\006Normal\020\000\022\r\n\tEmergency\020\001B\031\n\027top.itcat.p" +
                        "b_gen.commonb\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_BaseResponse_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_BaseResponse_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_BaseResponse_descriptor,
                new java.lang.String[]{"Code", "Msg",});
        internal_static_EmptyResponse_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_EmptyResponse_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_EmptyResponse_descriptor,
                new java.lang.String[]{"Base",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
