/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package top.itcat.rpc.service.model;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum PrescriptionItemStatusEnum implements org.apache.thrift.TEnum {
  Unattained(0),
  Attained(1),
  Return(2);

  private final int value;

  private PrescriptionItemStatusEnum(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static PrescriptionItemStatusEnum findByValue(int value) { 
    switch (value) {
      case 0:
        return Unattained;
      case 1:
        return Attained;
      case 2:
        return Return;
      default:
        return null;
    }
  }
}
